# Generated by Django 5.2.3 on 2025-06-20 01:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('raza', models.CharField(choices=[('Sin_Preferencia', 0), ('Bulldog_frances', 1), ('Bulldog', 2), ('Pitbull_terrier', 3), ('Busterrier', 4), ('Chihuahua', 5), ('Yorkshire', 6), ('Galgo', 7), ('Sharpei', 8), ('Shitsu', 9), ('Rottweiler', 10), ('Ovejero_aleman', 11), ('Border_collie', 12), ('Gran_danes', 13), ('Caniche', 14), ('Doberman', 15), ('Canecorso', 16), ('San_Bernardo', 17), ('Manto_Negro', 18), ('Pequines', 19), ('Terranova', 20), ('Mestizo', 21)], default='Mestizo', max_length=40)),
                ('edad', models.CharField(choices=[('Sin Preferencia', 0), ('Junior', 1), ('Adolesente', 2), ('Mayor', 3), ('Señior', 4)], default='Junior', max_length=20)),
                ('tamaño', models.CharField(choices=[('Sin Preferencia', 0), ('Pequeño', 1), ('Mediano', 2), ('Grande', 3)], default='Pequeño', max_length=20)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('vacunado', models.BooleanField(default=False)),
                ('estado', models.CharField(choices=[('disponible', 1), ('reservado', 2), ('adoptado', 3)], default='disponible', max_length=20)),
                ('temperamento', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PersonasAdoptantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=20, unique=True)),
                ('telefono', models.CharField(max_length=20)),
                ('direccion', models.TextField()),
                ('preferencias_raza', models.CharField(choices=[('Sin_Preferencia', 0), ('Bulldog_frances', 1), ('Bulldog', 2), ('Pitbull_terrier', 3), ('Busterrier', 4), ('Chihuahua', 5), ('Yorkshire', 6), ('Galgo', 7), ('Sharpei', 8), ('Shitsu', 9), ('Rottweiler', 10), ('Ovejero_aleman', 11), ('Border_collie', 12), ('Gran_danes', 13), ('Caniche', 14), ('Doberman', 15), ('Canecorso', 16), ('San_Bernardo', 17), ('Manto_Negro', 18), ('Pequines', 19), ('Terranova', 20), ('Mestizo', 21)], default='Sin_Preferencia', max_length=40)),
                ('preferencias_edad', models.CharField(choices=[('Sin Preferencia', 0), ('Junior', 1), ('Adolesente', 2), ('Mayor', 3), ('Señior', 4)], default='Junior', max_length=20)),
                ('preferencias_tamaño', models.CharField(choices=[('Sin Preferencia', 0), ('Pequeño', 1), ('Mediano', 2), ('Grande', 3)], default='Pequeño', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Adopcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_adopcion', models.DateTimeField(auto_now_add=True)),
                ('completada', models.BooleanField(default=False)),
                ('perro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adopciones.perro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adopciones.personasadoptantes')),
            ],
        ),
    ]
