# Generated by Django 5.2.3 on 2025-06-20 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perro',
            name='edad',
            field=models.CharField(choices=[(0, 'Sin Preferencia'), (1, 'Junior'), (2, 'Adolesente'), (3, 'Mayor'), (4, 'Señior')], default='Junior', max_length=20),
        ),
        migrations.AlterField(
            model_name='perro',
            name='raza',
            field=models.CharField(choices=[(0, 'Sin_Preferencia'), (1, 'Bulldog_frances'), (2, 'Bulldog'), (3, 'Pitbull_terrier'), (4, 'Busterrier'), (5, 'Chihuahua'), (6, 'Yorkshire'), (7, 'Galgo'), (8, 'Sharpei'), (9, 'Shitsu'), (10, 'Rottweiler'), (11, 'Ovejero_aleman'), (12, 'Border_collie'), (13, 'Gran_danes'), (14, 'Caniche'), (15, 'Doberman'), (16, 'Canecorso'), (17, 'San_Bernardo'), (18, 'Manto_Negro'), (19, 'Pequines'), (20, 'Terranova'), (21, 'Mestizo')], default='Mestizo', max_length=40),
        ),
        migrations.AlterField(
            model_name='perro',
            name='tamaño',
            field=models.CharField(choices=[(0, 'Sin Preferencia'), (1, 'Pequeño'), (2, 'Mediano'), (3, 'Grande')], default='Pequeño', max_length=20),
        ),
        migrations.AlterField(
            model_name='personasadoptantes',
            name='preferencias_edad',
            field=models.CharField(choices=[(0, 'Sin Preferencia'), (1, 'Junior'), (2, 'Adolesente'), (3, 'Mayor'), (4, 'Señior')], default='Junior', max_length=20),
        ),
        migrations.AlterField(
            model_name='personasadoptantes',
            name='preferencias_raza',
            field=models.CharField(choices=[(0, 'Sin_Preferencia'), (1, 'Bulldog_frances'), (2, 'Bulldog'), (3, 'Pitbull_terrier'), (4, 'Busterrier'), (5, 'Chihuahua'), (6, 'Yorkshire'), (7, 'Galgo'), (8, 'Sharpei'), (9, 'Shitsu'), (10, 'Rottweiler'), (11, 'Ovejero_aleman'), (12, 'Border_collie'), (13, 'Gran_danes'), (14, 'Caniche'), (15, 'Doberman'), (16, 'Canecorso'), (17, 'San_Bernardo'), (18, 'Manto_Negro'), (19, 'Pequines'), (20, 'Terranova'), (21, 'Mestizo')], default='Sin_Preferencia', max_length=40),
        ),
        migrations.AlterField(
            model_name='personasadoptantes',
            name='preferencias_tamaño',
            field=models.CharField(choices=[(0, 'Sin Preferencia'), (1, 'Pequeño'), (2, 'Mediano'), (3, 'Grande')], default='Pequeño', max_length=20),
        ),
    ]
