# Generated by Django 5.2.3 on 2025-06-20 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopciones', '0002_alter_perro_edad_alter_perro_raza_alter_perro_tamaño_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perro',
            name='estado',
            field=models.CharField(choices=[(1, 'disponible'), (2, 'reservado'), (3, 'adoptado')], default='disponible', max_length=20),
        ),
    ]
