# Generated by Django 5.2.3 on 2025-06-20 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopciones', '0003_alter_perro_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perro',
            name='edad',
            field=models.CharField(choices=[('Sin Preferencia', 'Sin Preferencia'), ('Junior', 'Junior'), ('Adolesente', 'Adolesente'), ('Mayor', 'Mayor'), ('Señior', 'Señior')], default='Junior', max_length=20),
        ),
        migrations.AlterField(
            model_name='perro',
            name='estado',
            field=models.CharField(choices=[('disponible', 'disponible'), ('reservado', 'reservado'), ('adoptado', 'adoptado')], default='disponible', max_length=20),
        ),
        migrations.AlterField(
            model_name='perro',
            name='raza',
            field=models.CharField(choices=[('Sin_Preferencia', 'Sin_Preferencia'), ('Bulldog_frances', 'Bulldog_frances'), ('Bulldog', 'Bulldog'), ('Pitbull_terrier', 'Pitbull_terrier'), ('Busterrier', 'Busterrier'), ('Chihuahua', 'Chihuahua'), ('Yorkshire', 'Yorkshire'), ('Galgo', 'Galgo'), ('Sharpei', 'Sharpei'), ('Shitsu', 'Shitsu'), ('Rottweiler', 'Rottweiler'), ('Ovejero_aleman', 'Ovejero_aleman'), ('Border_collie', 'Border_collie'), ('Gran_danes', 'Gran_danes'), ('Caniche', 'Caniche'), ('Doberman', 'Doberman'), ('Canecorso', 'Canecorso'), ('San_Bernardo', 'San_Bernardo'), ('Manto_Negro', 'Manto_Negro'), ('Pequines', 'Pequines'), ('Terranova', 'Terranova'), ('Mestizo', 'Mestizo')], default='Mestizo', max_length=40),
        ),
        migrations.AlterField(
            model_name='perro',
            name='tamaño',
            field=models.CharField(choices=[('Sin Preferencia', 'Sin Preferencia'), ('Pequeño', 'Pequeño'), ('Mediano', 'Mediano'), ('Grande', 'Grande')], default='Pequeño', max_length=20),
        ),
        migrations.AlterField(
            model_name='personasadoptantes',
            name='preferencias_edad',
            field=models.CharField(choices=[('Sin Preferencia', 'Sin Preferencia'), ('Junior', 'Junior'), ('Adolesente', 'Adolesente'), ('Mayor', 'Mayor'), ('Señior', 'Señior')], default='Junior', max_length=20),
        ),
        migrations.AlterField(
            model_name='personasadoptantes',
            name='preferencias_raza',
            field=models.CharField(choices=[('Sin_Preferencia', 'Sin_Preferencia'), ('Bulldog_frances', 'Bulldog_frances'), ('Bulldog', 'Bulldog'), ('Pitbull_terrier', 'Pitbull_terrier'), ('Busterrier', 'Busterrier'), ('Chihuahua', 'Chihuahua'), ('Yorkshire', 'Yorkshire'), ('Galgo', 'Galgo'), ('Sharpei', 'Sharpei'), ('Shitsu', 'Shitsu'), ('Rottweiler', 'Rottweiler'), ('Ovejero_aleman', 'Ovejero_aleman'), ('Border_collie', 'Border_collie'), ('Gran_danes', 'Gran_danes'), ('Caniche', 'Caniche'), ('Doberman', 'Doberman'), ('Canecorso', 'Canecorso'), ('San_Bernardo', 'San_Bernardo'), ('Manto_Negro', 'Manto_Negro'), ('Pequines', 'Pequines'), ('Terranova', 'Terranova'), ('Mestizo', 'Mestizo')], default='Sin_Preferencia', max_length=40),
        ),
        migrations.AlterField(
            model_name='personasadoptantes',
            name='preferencias_tamaño',
            field=models.CharField(choices=[('Sin Preferencia', 'Sin Preferencia'), ('Pequeño', 'Pequeño'), ('Mediano', 'Mediano'), ('Grande', 'Grande')], default='Pequeño', max_length=20),
        ),
    ]
