# Generated by Django 5.2.3 on 2025-06-20 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopciones', '0004_alter_perro_edad_alter_perro_estado_alter_perro_raza_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personasadoptantes',
            name='nombre',
            field=models.CharField(default='Sin nombre', max_length=100),
        ),
    ]
